# Generated by Django 3.1 on 2020-08-11 16:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('practicalApi', '0002_auto_20200811_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersOTP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('otp', models.CharField(max_length=4)),
            ],
        ),
    ]
