# Generated by Django 3.1 on 2020-08-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicalApi', '0004_auto_20200811_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersotp',
            name='otp',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='usersotp',
            name='timestamp',
            field=models.IntegerField(default=0),
        ),
    ]
